const Data = [
  {
    id: 1,
    img: "/imges/product_01.1.jpg",
    title: "Chicken Burger",
    price: "24$",
    category: "Burger",
  },
  {
    id: 2,
    img: "/imges/Vegetirian.jpg",
    title: "Vegetarian Pizza",
    price: "125$",
    category: "Pizza",
  },
  {
    id: 3,
    img: "/imges/double.jpg",
    title: "Double Chease Margerita",
    price: "120$",
    category: "Pizza",
  },
  {
    id: 4,
    img: "/public/imges/maxican.jpg",
    title: "Mixican Green Wave ",
    price: "110$",
    category: "Pizza",
  },
  {
    id: 6,
    img: "/public/imges/product_04.jpg",
    title: "Royal Cheese Burger",
    price: "54$",
    category: "Burger",
  },
  {
    id: 5,
    img: "/public/imges/product_01.jpg",
    title: "Cheese Burger",
    price: "44$",
    category: "Burger",
  },
  {
    id: 7,
    img: "/public/imges/seefood.jpg",
    title: " Seafood Pizza",
    price: "144$",
    category: "Pizza",
  },
  {
    id: 8,
    img: "/public/imges/product_3.2.jpg",
    title: "Thin Cheese Pizza",
    price: "100$",
    category: "Pizza",
  },
  {
    id: 9,
    img: "/public/imges/product_4.2.jpg",
    title: "Pizza With Mushroom",
    price: "88$",
    category: "Pizza",
  },
  {
    id: 10,
    img: "/public/imges/product_08.jpg",
    title: "Classic Burger",
    price: "24$",
    category: "Burger",
  },
  {
    id: 11,
    img: "/public/imges/bread(1).png",
    title: "Crunchy Bread",
    price: "34$",
    category: "Bread",
  },
  {
    id: 12,
    img: "/public/imges/bread(2).png",
    title: "Delicious Bread",
    price: "43$",
    category: "Bread",
  },
  {
    id: 13,
    img: "/public/imges/bread(3).png",
    title: "Loaf Bread",
    price: "35$",
    category: "Bread",
  },
  {
    id: 14,
    img: "/public/imges/product_09.jpg",
    title: "Cheese Burger",
    price: "35$",
    category: "Burger",
  },
  {
    id: 15,
    img: "/public/imges/product_4.3.png",
    title: "Bebrony Pizza",
    price: "35$",
    category: "Pizza",
  },
  {
    id: 16,
    img: "/public/imges/product_3.3.jpg",
    title: "Vegetable Pizza",
    price: "35$",
    category: "Pizza",
  },
];
export default Data;
